export const appSettings = {
  IS_PUBLIC_KEY: 'isPublic',
  ACCESS_TOKEN_SERVICE: 'ACCESS_TOKEN_SERVICE',
  REFRESH_TOKEN_SERVICE: 'REFRESH_TOKEN_SERVICE',
  ACCESS_TOKEN_STRATEGY: 'ACCESS_TOKEN_STRATEGY',
  REFRESH_TOKEN_STRATEGY: 'REFRESH_TOKEN_STRATEGY',
  MAIN_PATHS: {
    BLOGS: '/blogs',
    POSTS: '/posts',
    TESTS: '/testing',
    USERS: '/users',
    AUTH: '/auth',
    COMMENTS: '/comments',
    SECURITY: '/security',
  },
  ENDPOINT_PATHS: {
    AUTH: {
      LOGIN: '/login',
      LOGOUT: '/logout',
      PASSWORD_RECOVERY: '/password-recovery',
      CONFIRM_PASSWORD_RECOVERY: '/new-password',
      REFRESH_TOKEN: '/refresh-token',
      REGISTRATION: '/registration',
      REGISTRATION_CONFIRMATION: '/registration-confirmation',
      REGISTRATION_EMAIL_RESENDING: '/registration-email-resending',
      ME: '/me',
    },
    DEVICES: {
      GET_DEVICES: 'devices',
      DELETE_DEVICES: 'devices',
      DELETE_DEVICE: 'devices/:id',
    },
  },
  CLEAR_COLLETIONS_PATH: '/testing/all-data',
};
